export const eventConstants = {
  EVENT_REQUEST: "EVENT_REQUEST",
  EVENT_SUCCESS: "EVENT_SUCCESS",
  EVENT_FAILURE: "EVENT_FAILURE",

  EVENT_GETALL_REQUEST: "EVENT_GETALL_REQUEST",
  EVENT_GETALL_SUCCESS: "EVENT_GETALL_SUCCESS",
  EVENT_GETALL_FAILURE: "EVENT_GETALL_FAILURE",

  EVENT_CREATE_REQUEST: "EVENT_CREATE_REQUEST",
  EVENT_CREATE_SUCCESS: "EVENT_CREATE_SUCCESS",
  EVENT_CREATE_FAILURE: "EVENT_CREATE_FAILURE",

  EVENT_DELETE_REQUEST: "EVENT_DELETE_REQUEST",
  EVENT_DELETE_SUCCESS: "EVENT_DELETE_SUCCESS",
  EVENT_DELETE_FAILURE: "EVENT_DELETE_FAILURE",
};
